[package]
name = "kingdom_sim"
version = "0.0.1"
publish = false
authors = ["azuresplash@gmail.com"]
edition = "2021"

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1

[profile.release]
lto = true
codegen-units = 1

[features]
default = [
    "bevy/bevy_winit",
    "bevy/render",
    "bevy/png",
    "bevy/x11",
    "bevy_kira_audio/ogg",
]

dev = ["bevy/dynamic"]

[dependencies]
bevy = { version = "0.9", default-features = false }
bevy_kira_audio = { version = "0.13" }
bevy_asset_loader = { version = "0.14" }
rand = "0.8"
itertools = "0.10"
conditional_commands = "0.7"
bevy_common_assets = { version = "0.4", features = ["json"] }
serde = "1.0"

[target.'cfg(target_os = "linux")'.dependencies]
winit = { version = "0.27", features = ["x11"] }

[build-dependencies]
embed-resource = "1.7"
